[package]
name = "testgen-js"
version = "0.1.0"
authors = ["Koki Takahashi <hakatasiloving@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
